version: '3.8'

services:
  app:
    image: tech-movement/backend-tech-movement/uat:v1.0.1
    environment:
      - MONGO_URI=mongodb://localhost:27017/
      - DB_NAME_MONGOD=techmovement
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=localhost:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0