basePath: /api
host: localhost:5050
info:
  contact: {}
  description: This is a sample server for a News API.
  version: "1.0"
paths: {}
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
