basePath: /api
definitions:
  domain.Category:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  domain.ErrResponse:
    properties:
      error:
        type: string
    type: object
  domain.News:
    properties:
      category:
        $ref: '#/definitions/domain.Category'
      created_at:
        type: string
      detail:
        type: string
      id:
        type: string
      image:
        type: string
      tag:
        items:
          type: string
        type: array
      title:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:5050
info:
  contact: {}
  description: This is a sample server for a News API.
  title: News API
  version: "1.0"
paths:
  /news:
    get:
      consumes:
      - application/json
      description: ดึงข้อมูลข่าวแบบ pagination โดยดึงจาก lastid กล่าวคือหากใส่ id
        ของข่าวแล้วหลังจาก id ลงไปนั้นตาม limit
      parameters:
      - description: ID of the last news item from the previous page
        in: query
        name: lastID
        type: string
      - description: 'Number of news per page (default: 10)'
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.News'
        "400":
          description: Invalid request parameters
          schema:
            $ref: '#/definitions/domain.ErrResponse'
        "500":
          description: Cannot Fetch Data.
          schema:
            $ref: '#/definitions/domain.ErrResponse'
      security:
      - ApiKeyAuth: []
      summary: Get News Pagination
      tags:
      - news
    post:
      consumes:
      - application/json
      description: api สร้างหน้าข่าวใหม่
      parameters:
      - description: News Data
        in: body
        name: news
        required: true
        schema:
          $ref: '#/definitions/domain.News'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.News'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/domain.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrResponse'
      security:
      - ApiKeyAuth: []
      summary: Create a New News
      tags:
      - news
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
